/**
 */
package IECFieldOfActivityAnnotations.provider;

import IECFieldOfActivityAnnotations.util.IECFieldOfActivityAnnotationsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class IECFieldOfActivityAnnotationsItemProviderAdapterFactory extends IECFieldOfActivityAnnotationsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IECFieldOfActivityAnnotationsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECFieldOfActivityAnnotationsRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECFieldOfActivityAnnotationsRepositoryItemProvider iecFieldOfActivityAnnotationsRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECFieldOfActivityAnnotationsRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECFieldOfActivityAnnotationsRepositoryAdapter() {
		if (iecFieldOfActivityAnnotationsRepositoryItemProvider == null) {
			iecFieldOfActivityAnnotationsRepositoryItemProvider = new IECFieldOfActivityAnnotationsRepositoryItemProvider(this);
		}

		return iecFieldOfActivityAnnotationsRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECDevelopmentArtefactSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECDevelopmentArtefactSpecificationItemProvider iecDevelopmentArtefactSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECDevelopmentArtefactSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECDevelopmentArtefactSpecificationAdapter() {
		if (iecDevelopmentArtefactSpecificationItemProvider == null) {
			iecDevelopmentArtefactSpecificationItemProvider = new IECDevelopmentArtefactSpecificationItemProvider(this);
		}

		return iecDevelopmentArtefactSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECSourceFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECSourceFileItemProvider iecSourceFileItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECSourceFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECSourceFileAdapter() {
		if (iecSourceFileItemProvider == null) {
			iecSourceFileItemProvider = new IECSourceFileItemProvider(this);
		}

		return iecSourceFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECSourceFileAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECSourceFileAggregationItemProvider iecSourceFileAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECSourceFileAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECSourceFileAggregationAdapter() {
		if (iecSourceFileAggregationItemProvider == null) {
			iecSourceFileAggregationItemProvider = new IECSourceFileAggregationItemProvider(this);
		}

		return iecSourceFileAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECMetadataFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECMetadataFileItemProvider iecMetadataFileItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECMetadataFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECMetadataFileAdapter() {
		if (iecMetadataFileItemProvider == null) {
			iecMetadataFileItemProvider = new IECMetadataFileItemProvider(this);
		}

		return iecMetadataFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECMetadataFileAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECMetadataFileAggregationItemProvider iecMetadataFileAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECMetadataFileAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECMetadataFileAggregationAdapter() {
		if (iecMetadataFileAggregationItemProvider == null) {
			iecMetadataFileAggregationItemProvider = new IECMetadataFileAggregationItemProvider(this);
		}

		return iecMetadataFileAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECTestSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECTestSpecificationItemProvider iecTestSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECTestSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECTestSpecificationAdapter() {
		if (iecTestSpecificationItemProvider == null) {
			iecTestSpecificationItemProvider = new IECTestSpecificationItemProvider(this);
		}

		return iecTestSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECDeploymentSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECDeploymentSpecificationItemProvider iecDeploymentSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECDeploymentSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECDeploymentSpecificationAdapter() {
		if (iecDeploymentSpecificationItemProvider == null) {
			iecDeploymentSpecificationItemProvider = new IECDeploymentSpecificationItemProvider(this);
		}

		return iecDeploymentSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECRuntimeInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECRuntimeInstanceItemProvider iecRuntimeInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECRuntimeInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECRuntimeInstanceAdapter() {
		if (iecRuntimeInstanceItemProvider == null) {
			iecRuntimeInstanceItemProvider = new IECRuntimeInstanceItemProvider(this);
		}

		return iecRuntimeInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECRuntimeInstanceAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECRuntimeInstanceAggregationItemProvider iecRuntimeInstanceAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECRuntimeInstanceAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECRuntimeInstanceAggregationAdapter() {
		if (iecRuntimeInstanceAggregationItemProvider == null) {
			iecRuntimeInstanceAggregationItemProvider = new IECRuntimeInstanceAggregationItemProvider(this);
		}

		return iecRuntimeInstanceAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECUnitTestCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECUnitTestCaseItemProvider iecUnitTestCaseItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECUnitTestCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECUnitTestCaseAdapter() {
		if (iecUnitTestCaseItemProvider == null) {
			iecUnitTestCaseItemProvider = new IECUnitTestCaseItemProvider(this);
		}

		return iecUnitTestCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECAcceptanceTestCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECAcceptanceTestCaseItemProvider iecAcceptanceTestCaseItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECAcceptanceTestCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECAcceptanceTestCaseAdapter() {
		if (iecAcceptanceTestCaseItemProvider == null) {
			iecAcceptanceTestCaseItemProvider = new IECAcceptanceTestCaseItemProvider(this);
		}

		return iecAcceptanceTestCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECIntegrationTestCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECIntegrationTestCaseItemProvider iecIntegrationTestCaseItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECIntegrationTestCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECIntegrationTestCaseAdapter() {
		if (iecIntegrationTestCaseItemProvider == null) {
			iecIntegrationTestCaseItemProvider = new IECIntegrationTestCaseItemProvider(this);
		}

		return iecIntegrationTestCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECUnitTestCaseAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECUnitTestCaseAggregationItemProvider iecUnitTestCaseAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECUnitTestCaseAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECUnitTestCaseAggregationAdapter() {
		if (iecUnitTestCaseAggregationItemProvider == null) {
			iecUnitTestCaseAggregationItemProvider = new IECUnitTestCaseAggregationItemProvider(this);
		}

		return iecUnitTestCaseAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECAcceptanceTestCaseAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECAcceptanceTestCaseAggregationItemProvider iecAcceptanceTestCaseAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECAcceptanceTestCaseAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECAcceptanceTestCaseAggregationAdapter() {
		if (iecAcceptanceTestCaseAggregationItemProvider == null) {
			iecAcceptanceTestCaseAggregationItemProvider = new IECAcceptanceTestCaseAggregationItemProvider(this);
		}

		return iecAcceptanceTestCaseAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECIntegrationTestCaseAggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECIntegrationTestCaseAggregationItemProvider iecIntegrationTestCaseAggregationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECIntegrationTestCaseAggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECIntegrationTestCaseAggregationAdapter() {
		if (iecIntegrationTestCaseAggregationItemProvider == null) {
			iecIntegrationTestCaseAggregationItemProvider = new IECIntegrationTestCaseAggregationItemProvider(this);
		}

		return iecIntegrationTestCaseAggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECStaffSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECStaffSpecificationItemProvider iecStaffSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECStaffSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECStaffSpecificationAdapter() {
		if (iecStaffSpecificationItemProvider == null) {
			iecStaffSpecificationItemProvider = new IECStaffSpecificationItemProvider(this);
		}

		return iecStaffSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECPersonList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECPersonListItemProvider iecPersonListItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECPersonList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECPersonListAdapter() {
		if (iecPersonListItemProvider == null) {
			iecPersonListItemProvider = new IECPersonListItemProvider(this);
		}

		return iecPersonListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECPerson} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECPersonItemProvider iecPersonItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECPerson}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECPersonAdapter() {
		if (iecPersonItemProvider == null) {
			iecPersonItemProvider = new IECPersonItemProvider(this);
		}

		return iecPersonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECRoleList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECRoleListItemProvider iecRoleListItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECRoleList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECRoleListAdapter() {
		if (iecRoleListItemProvider == null) {
			iecRoleListItemProvider = new IECRoleListItemProvider(this);
		}

		return iecRoleListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECDeveloper} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECDeveloperItemProvider iecDeveloperItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECDeveloper}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECDeveloperAdapter() {
		if (iecDeveloperItemProvider == null) {
			iecDeveloperItemProvider = new IECDeveloperItemProvider(this);
		}

		return iecDeveloperItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECTestDeveloper} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECTestDeveloperItemProvider iecTestDeveloperItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECTestDeveloper}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECTestDeveloperAdapter() {
		if (iecTestDeveloperItemProvider == null) {
			iecTestDeveloperItemProvider = new IECTestDeveloperItemProvider(this);
		}

		return iecTestDeveloperItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECTester} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECTesterItemProvider iecTesterItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECTester}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECTesterAdapter() {
		if (iecTesterItemProvider == null) {
			iecTesterItemProvider = new IECTesterItemProvider(this);
		}

		return iecTesterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IECFieldOfActivityAnnotations.IECDeployer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IECDeployerItemProvider iecDeployerItemProvider;

	/**
	 * This creates an adapter for a {@link IECFieldOfActivityAnnotations.IECDeployer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIECDeployerAdapter() {
		if (iecDeployerItemProvider == null) {
			iecDeployerItemProvider = new IECDeployerItemProvider(this);
		}

		return iecDeployerItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (iecFieldOfActivityAnnotationsRepositoryItemProvider != null) iecFieldOfActivityAnnotationsRepositoryItemProvider.dispose();
		if (iecDevelopmentArtefactSpecificationItemProvider != null) iecDevelopmentArtefactSpecificationItemProvider.dispose();
		if (iecSourceFileItemProvider != null) iecSourceFileItemProvider.dispose();
		if (iecSourceFileAggregationItemProvider != null) iecSourceFileAggregationItemProvider.dispose();
		if (iecMetadataFileItemProvider != null) iecMetadataFileItemProvider.dispose();
		if (iecMetadataFileAggregationItemProvider != null) iecMetadataFileAggregationItemProvider.dispose();
		if (iecTestSpecificationItemProvider != null) iecTestSpecificationItemProvider.dispose();
		if (iecDeploymentSpecificationItemProvider != null) iecDeploymentSpecificationItemProvider.dispose();
		if (iecRuntimeInstanceItemProvider != null) iecRuntimeInstanceItemProvider.dispose();
		if (iecRuntimeInstanceAggregationItemProvider != null) iecRuntimeInstanceAggregationItemProvider.dispose();
		if (iecUnitTestCaseItemProvider != null) iecUnitTestCaseItemProvider.dispose();
		if (iecAcceptanceTestCaseItemProvider != null) iecAcceptanceTestCaseItemProvider.dispose();
		if (iecIntegrationTestCaseItemProvider != null) iecIntegrationTestCaseItemProvider.dispose();
		if (iecUnitTestCaseAggregationItemProvider != null) iecUnitTestCaseAggregationItemProvider.dispose();
		if (iecAcceptanceTestCaseAggregationItemProvider != null) iecAcceptanceTestCaseAggregationItemProvider.dispose();
		if (iecIntegrationTestCaseAggregationItemProvider != null) iecIntegrationTestCaseAggregationItemProvider.dispose();
		if (iecStaffSpecificationItemProvider != null) iecStaffSpecificationItemProvider.dispose();
		if (iecPersonListItemProvider != null) iecPersonListItemProvider.dispose();
		if (iecPersonItemProvider != null) iecPersonItemProvider.dispose();
		if (iecRoleListItemProvider != null) iecRoleListItemProvider.dispose();
		if (iecDeveloperItemProvider != null) iecDeveloperItemProvider.dispose();
		if (iecTestDeveloperItemProvider != null) iecTestDeveloperItemProvider.dispose();
		if (iecTesterItemProvider != null) iecTesterItemProvider.dispose();
		if (iecDeployerItemProvider != null) iecDeployerItemProvider.dispose();
	}

}
