<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Modifikationmarks" nsURI="http://www.example.org/Modifikationmarks"
    nsPrefix="Modifikationmarks">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractKAMP4IECModificationRepository"
      abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//KAMP4IECSeedModifications"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KAMP4IECModificationRepository">
    <eGenericSuperTypes eClassifier="#//AbstractKAMP4IECModificationRepository">
      <eTypeArguments eClassifier="#//KAMP4IECSeedModifications"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KAMP4IECSeedModifications">
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariableModifications"
        upperBound="-1" eType="#//ModifyGlobalVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionblockModifications"
        upperBound="-1" eType="#//ModifyFunctionBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangePropagationDueToDataDeploy"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4iec.model/model/IECModel.ecore#//Element"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyGlobalVariable">
    <eGenericSuperTypes eClassifier="#//ModifyElement">
      <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4iec.model/model/IECModel.ecore#//GlobalVariable"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyFunctionBlock">
    <eGenericSuperTypes eClassifier="#//ModifyElement">
      <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4iec.model/model/IECModel.ecore#//FunctionBlock"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
